"""Offscreen MuJoCo rendering using OSMesa."""

import base64
import io
import mujoco
import numpy as np
from PIL import Image

from .simulation import SimConfig, _get_model_name, _spiral_tube_position


def render_frames(
    mjcf_xml: str,
    config: SimConfig,
    width: int = 640,
    height: int = 480,
    camera_name: str | None = "side",
    max_frames: int = 100,
) -> list[str]:
    """Render simulation frames as base64-encoded PNGs.

    For scripted scenarios (spiral_tube), sets ball position programmatically
    to match the trajectory generated by run_simulation.
    """
    model = mujoco.MjModel.from_xml_string(mjcf_xml)
    data = mujoco.MjData(model)
    model_name = _get_model_name(mjcf_xml)

    # Apply damping override
    if config.damping > 0:
        for i in range(model.njnt):
            model.jnt_damping[i] = config.damping

    # Set initial velocity (for non-scripted scenarios)
    if model.nq >= 7:
        data.qvel[0] = config.initial_vx
        data.qvel[1] = config.initial_vy
        data.qvel[2] = config.initial_vz

    # Set up renderer
    renderer = mujoco.Renderer(model, height=height, width=width)

    total_steps = int(config.duration / model.opt.timestep)
    frame_interval = max(1, total_steps // max_frames)

    frames = []
    step = 0
    scripted = model_name in ("spiral_tube",)

    while data.time < config.duration:
        if scripted and model_name == "spiral_tube":
            x, y, z, vx, vy, vz = _spiral_tube_position(
                data.time, config.duration, speed=config.initial_vx or 2.0
            )
            if model.nq >= 7:
                data.qpos[0] = x
                data.qpos[1] = y
                data.qpos[2] = z
                data.qvel[0] = vx
                data.qvel[1] = vy
                data.qvel[2] = vz
            mujoco.mj_forward(model, data)
            data.time += model.opt.timestep
        else:
            # Standard MuJoCo physics
            if data.time >= config.force_start_time and model.nu > 0:
                data.ctrl[0] = config.force_magnitude
            elif model.nu > 0:
                data.ctrl[0] = 0.0

            mujoco.mj_step(model, data)

        step += 1

        if step % frame_interval == 0 and len(frames) < max_frames:
            renderer.update_scene(data, camera=camera_name)
            pixels = renderer.render()

            # Convert to base64 PNG
            img = Image.fromarray(pixels)
            buf = io.BytesIO()
            img.save(buf, format="PNG", optimize=True)
            b64 = base64.b64encode(buf.getvalue()).decode("ascii")
            frames.append(b64)

    renderer.close()
    return frames
